apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stirbul
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/myty844-hash/stirbul
    targetRevision: main
    path: dep
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
