apiVersion: apps/v1
kind: Deployment
metadata:
  name: stirbul-site
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stirbul-site
  template:
    metadata:
      labels:
        app: stirbul-site
    spec:
      containers:
        - name: stirbul-web
          image: nikibiki12/hello:v6
          imagePullPolicy: IfNotPresent
          env:
            - name: SQLSERVER_HOST
              value: "10.100.102.94"
            - name: SQLSERVER_PORT
              value: "1433"
            - name: SQLSERVER_USER
              value: "sa"
            - name: SQLSERVER_PASSWORD
              value: "YourStrongPassword123!"
            - name: SQLSERVER_QUERY
              value: "SELECT TOP 5 * FROM amitai"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: stirbul-service
  namespace: default
spec:
  selector:
    app: stirbul-site
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30084
  type: NodePort
