apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-sql-backup
spec:
  schedule: {{ .Values.cronjob.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: sql-executor
              image: "mcr.microsoft.com/mssql-tools:latest"
              env:
                {{- range $key, $val := .Values.env }}
                {{- if ne $key "SQLSERVER_QUERY" }}
                - name: {{ $key }}
                  value: {{ $val | quote }}
                {{- end }}
                {{- end }}
              command: ["/bin/bash", "-c"]
              args:
                - |
                  set -e # Exit immediately if a command fails
                  
                  echo "Downloading Ola Hallengren's Maintenance Solution..."
                  curl -sL https://ola.hallengren.com/scripts/MaintenanceSolution.sql -o /tmp/ola.sql
                  
                  echo "Installing/Updating Maintenance Procedures..."
                  /opt/mssql-tools/bin/sqlcmd \
                    -S "$SQLSERVER_HOST,$SQLSERVER_PORT" \
                    -U "$SQLSERVER_USER" \
                    -P "$SQLSERVER_PASSWORD" \
                    -d master -i /tmp/ola.sql

                  echo "Starting FULL Backup..."
                  /opt/mssql-tools/bin/sqlcmd \
                    -S "$SQLSERVER_HOST,$SQLSERVER_PORT" \
                    -U "$SQLSERVER_USER" \
                    -P "$SQLSERVER_PASSWORD" \
                    -d master -Q \
                  "EXECUTE [dbo].[DatabaseBackup] 
                    @Databases = 'USER_DATABASES', 
                    @Directory = '/var/opt/mssql/backups', 
                    @BackupType = 'FULL', 
                    @Verify = 'Y'"
          restartPolicy: OnFailure